#!/bin/bash
open() {
  sel=$(cleanup_sel "$PARENT_SEL")
  full="$PARENT_PWD/$sel"
  [[ -f $sel ]] && pathescaped="$(printf "%b\n" "${sel//%/\\x}")" ||
    pathescaped="$(printf "%b\n" "${full//%/\\x}")"
  setsid xdg-open "$pathescaped" >/dev/null 2>&1 &
}

cleanup_sel() {
  sed "s/^[[:space:]]*//;s/[[:space:]]*$//;s/^'//;s/^\"//;s/'$//;s/\"$//" <<< "$1"
}

urlregex="(((http|https|gopher|gemini|ftp|ftps|git)://|www\\.)[a-zA-Z0-9.]*[:]?[a-zA-Z0-9./@$&%?$\#=_~-]*)|((magnet:\\?xt=urn:btih:)[a-zA-Z0-9]*)"

url="$(sed 's/.*│//g' <<< "$PARENT_SEL"| # First remove mutt sidebars:
  grep -aEo "$urlregex" | # grep only urls as defined above.
  uniq | # Ignore neighboring duplicates.
  sed "s/\(\.\|,\|;\|\!\\|\?\)$//;
  s/^www./http:\/\/www\./")" # xdg-open will not detect url without http

[ -z "$url" ] && ( [[ -n $PARENT_SEL ]] && open) || xdg-open "$url"
