#!/bin/bash
# requires https://metacpan.org/pod/Regexp::Common::URI
open() {
  setsid xdg-open "$1" >/dev/null 2>&1 &
}
urlregex="(((http|https|gopher|gemini|ftp|ftps|git)://|www\\.)[a-zA-Z0-9.]*[:]?[a-zA-Z0-9./@$&%?$\#=_~-]*)|((magnet:\\?xt=urn:btih:)[a-zA-Z0-9]*)"

url="$(sed 's/.*│//g' <<< "$1"| # First remove mutt sidebars:
  grep -aEo "$urlregex" | # grep only urls as defined above.
  uniq | # Ignore neighboring duplicates.
  sed "s/\(\.\|,\|;\|\!\\|\?\)$//;
  s/^www./http:\/\/www\./")" # xdg-open will not detect url without http

[ -z $url ] && ( [[ -n $1 ]] && open "$2/$1") || open "$url"

# notify-send -t 2000 -u critical st-plumber "Selection is not a valid file or url!"
