#!/bin/bash

parent="$(pgrep -lP $PPID | awk 'FNR == 1 {print $0}')"
grandparent="$(pgrep -lP "$(awk 'FNR == 1 {print $1}' <<< "$parent")")"

case "$(awk '{print $2}' <<< "$parent")" in
  nvim|vim|vi|"$EDITOR")
    exit ;;
esac

case "$(awk '{print $2}' <<< "$grandparent")" in
  nvim|vim|vi|"$EDITOR")
    exit ;;
esac

tmpfile=$(mktemp /tmp/st-cmd-output.XXXXXX)
trap 'rm "$tmpfile"' 0 1 15
cat >"$tmpfile"
while getopts "vwsl" o; do case "${o}" in
  v) st -t "st-vimmode" -e nvim -u ~/.config/nvim/init_st_vimmode.vim -c "sleep 5ms; normal G \$" "$tmpfile" -M ;;
  w) st -t "st-vimmode" -e nvim -u ~/.config/nvim/init_st_vimmode.vim -c "sleep 5ms; normal G \$" -c "lua require'hop'.hint_words()" "$tmpfile" -M ;;
  s) st -t "st-vimmode" -e nvim -u ~/.config/nvim/init_st_vimmode.vim -c "sleep 5ms; normal G \$" -c "lua require'hop'.hint_patterns()" "$tmpfile" -M ;;
  l) st -t "st-vimmode" -e nvim -u ~/.config/nvim/init_st_vimmode.vim -c "sleep 5ms; normal G \$" -c "lua require'hop'.hint_lines()" "$tmpfile" -M ;;
  *) exit ;;
esac done
