#!/bin/bash

for (( d=0; d<=10; d++ )); do
  [[ d -eq 0 ]] && p=$PPID || p=$(awk '{print $1}' <<< "$parent")
  parent="$(pgrep -lP "$p" | awk 'FNR == 1 {print $0}')"
  case "$(awk '{print $2}' <<< "$parent")" in
    nvim|vim|vi|"$EDITOR")
      exit ;;
  esac
done

cd "$PARENT_PWD" || exit

tmpfile=$(mktemp /tmp/st-cmd-output.XXXXXX)
trap 'rm "$tmpfile"' 0 1 15
cat >"$tmpfile"
while getopts "vwsl" o; do case "${o}" in
  #MK_PATH is set by make
  #v) st -u "8-112" -t "st-vimmode" -e nvim -u MK_PATH/st-vim.vim -c "normal G \$" "$tmpfile" -M ;;
  v) st -u "8-112" -t "st-vimmode" -e nvim -u MK_PATH/st-vim.vim -c "normal G \$" -c "sleep 1ms" -c "lua require'hop'.hint_words()" "$tmpfile" -M ;;
  w) st -u "8-112" -t "st-vimmode" -e nvim -u MK_PATH/st-vim.vim -c "normal G \$" -c "sleep 1ms" -c "lua require'hop'.hint_words()" "$tmpfile" -M ;;
  s) st -u "8-112" -t "st-vimmode" -e nvim -u MK_PATH/st-vim.vim -c "normal G \$" -c "sleep 1ms" -c "lua require'hop'.hint_patterns()" "$tmpfile" -M ;;
  l) st -u "8-112" -t "st-vimmode" -e nvim -u MK_PATH/st-vim.vim -c "normal G \$" -c "sleep 1ms" -c "lua require'hop'.hint_lines()" "$tmpfile" -M ;;
  *) exit ;;
esac done
